<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<body>

<h2>Different Types of Go Boards</h2>
<p>Go is considered by many to be the oldest board game in the world that is still played. It is thought to be somewhere between 2,000 and over 4,000 years old.
    The object of the game is for two players to compete to surround the most territory by alternating placing black or white stones one at a time.
</p>
<div id = "gallery">
<img src="boardWithStones.jpg" class="mediumPicture"/>
<a href='https://photos.google.com/share/AF1QipOj8S-MGrIJLj9HgVWNkjQtdp7arx1rtvIjOhDCqplZ-3VUkTjfF5GfhO4YV38-Sw?key=TEtLR0hGY1p2MWFGQUwtcXdldDRUblhzWDJrQmlR&source=ctrlq.org'><img src='https://lh3.googleusercontent.com/v-kONDMSk-hswmpnLdxuhy9M1CMAY_Tf4l3heflHi3HNNKkA3AmIUHRq_lbnZw3018CKxgOf32NcKeh0eCnEaFDjqIIGl9H7EE3Ah7Ll1jiBXwPwoChqCdigD7zY4AUlV5dRJO5w=w2400' class="mediumPicture"/></a>
<div>
</body>
</html>
</html>